let language = 'en';

const turkish = {
  "Changes are saved as you type.": "Değişiklikler yazdıkça kaydedilir.",
  "Calculating…": "Hesaplanıyor…",
  "Remove cost item: {0}": "{0} kalemini sil",
  "New cost item": "Yeni maliyet kalemi",
  "e.g. Transport": "Örn. Nakliye",
  "+ Add item": "+ Kalem ekle",
  "Add your own costs. Use × in a column heading to remove an item.": "Kendi maliyetlerini ekle. Kalemi kaldırmak için sütun başlığındaki × işaretine bas.",
  "{0} change": "{0} değişimi",
  "Cost items changed. Calculate again to update all scenarios.": "Kalemler değişti. Tüm senaryoları güncellemek için tekrar hesapla.",
  "Remove {0}? Its monthly amounts and saved scenario changes will be deleted.": "{0} kaldırılsın mı? Aylık tutarları ve kayıtlı senaryolardaki değişimleri silinecek.",
  "Enter a new, different cost item name.": "Boş olmayan, farklı bir kalem adı gir.",
  "The project file has invalid cost items.": "Proje dosyasındaki maliyet kalemleri geçersiz.",
  "Cost item to check": "Kontrol edilecek kalem",
  "{0} rise → loss": "{0} artışı → zarar",

  "Compare costs, profit and cash needs for a construction project.": "İnşaat projenizin aylık giderlerini, kârını ve nakit ihtiyacını hesaplayın.",
  "Construction Calculator": "Proje hesabı",
  "Skip to content": "İçeriğe geç",
  "COSTS & CASH FLOW": "MALİYET & NAKİT AKIŞI",
  "Plan the costs. Try a few scenarios. See how the numbers change.": "İşin gelirini ve giderini planla, nakit ihtiyacını gör.",
  "Open file": "Dosyadan aç",
  "Save file": "Dosyaya kaydet",
  "Load example": "Örnek verileri yükle",
  "Currency": "Para birimi",
  "US dollar (USD)": "Dolar (USD)",
  "Turkish lira (TL)": "Türk lirası (TL)",
  "Changes the currency label only. No exchange rate conversion.": "Yalnızca para birimi etiketi değişir; kur dönüşümü yapılmaz.",
  "This is a made-up example. Change the numbers to try your own project.": "Kurgusal bir örnek proje açık. Tutarları kendi projenize göre değiştirebilirsiniz.",
  "Project details": "Proje bilgileri",
  "Project name": "Proje adı",
  "e.g. Housing project": "Örn. Konut projesi",
  "Contract value": "Sözleşme bedeli",
  "Work duration": "İş süresi",
  "Payment delay": "Tahsilat gecikmesi",
  "Starting cash": "Başlangıç nakdi",
  "Monthly overhead": "Aylık genel gider",
  "Monthly loan interest": "Aylık kredi faizi",
  "Overhead is added each working month. Do not add it again in the cost columns. Dots separate thousands; use a comma for cents.": "Genel gider her çalışma ayına ayrıca eklenir. Maliyet sütunlarına tekrar yazmayın. Binlik noktaları otomatik eklenir; kuruş için virgül kullanın.",
  "Monthly plan": "Aylık iş planı",
  "All amounts in": "Tüm tutarlar",
  "Enter the amount billed and costs for each month.": "Hakediş ve maliyetleri ay bazında düzenleyin.",
  "Split billing evenly": "Hakedişleri eşit dağıt",
  "Editable monthly plan": "Düzenlenebilir aylık iş planı",
  "Monthly billing and costs,": "Aylık hakediş ve maliyet girişleri,",
  "Billed is the value of work done that month. Payment arrives later if a delay is set.": "Hakediş, yapılan işin bedelidir. Tahsilat, gecikme süresine göre sonraki aylara aktarılır.",
  "What if things change?": "Koşullar değişirse?",
  "Try stress example": "Örnek stres testi",
  "Reset fields": "Alanları sıfırla",
  "Set the changes, give the scenario a name and add it to the comparison. Then try another combination. Leave unchanged fields at 0. Use a negative percentage for lower costs.": "Koşulları gir, isim ver ve karşılaştırmaya ekle. Ardından başka bir kombinasyon hazırla. Değişmeyecek alanları 0 bırak; maliyet düşüşü için negatif yüzde gir.",
  "Steel change": "Demir değişimi",
  "Concrete change": "Beton değişimi",
  "Labour change": "İşçilik değişimi",
  "Extra payment delay": "Ek tahsilat gecikmesi",
  "Extra work months": "İş süresi uzaması",
  "Scenario name": "Senaryo adı",
  "(optional)": "(isteğe bağlı)",
  "e.g. Steel + labour": "Örn. Demir + işçilik",
  "Add to comparison": "Karşılaştırmaya ekle",
  "Saved scenarios": "Karşılaştırmaya eklenen senaryolar",
  "Changes apply to the whole project. Extra delay is added to the base delay. Extra months spread the same work over a longer period and add more overhead. Labour costs only change with the percentage you enter.": "Yüzdeler planın tamamına uygulanır. Ek gecikme, baz gecikmeye eklenir. Süre uzarsa iş ve hakedişler yeni takvime orantılı yayılır; genel gider ek aylarda sürer. İşçilik bütçesi yalnızca girilen yüzdeyle değişir.",
  "Setting up local save.": "Otomatik kayıt hazırlanıyor.",
  "Clear form": "Formu temizle",
  "Calculate project": "Projeyi hesapla",
  "BASE CASE": "BAZ HESAP",
  "Project summary": "Projenin özeti",
  "Inputs changed. Click Calculate project to update the results.": "Girdiler değişti. Güncel sonuçlar için “Projeyi hesapla” düğmesine basın.",
  "Summary and monthly details": "Kartlar ve aylık döküm",
  "The comparison table includes every scenario. Use the chart buttons to show or hide lines.": "Tabloda tüm senaryolar gösterilir. Grafik çizgilerini adlarına basarak açıp kapatabilirsiniz.",
  "Profit before tax": "Vergi öncesi kâr",
  "After costs and loan interest": "Giderler ve finansman sonrası",
  "Profit margin": "Kâr marjı",
  "As a share of the contract value": "Sözleşme bedeline göre",
  "Peak borrowing": "En yüksek kredi ihtiyacı",
  "Loan interest cost": "Finansman maliyeti",
  "Total interest over the project": "Hesap dönemi boyunca toplam faiz",
  "Compare scenarios": "Baz ve senaryo karşılaştırması",
  "Base and scenario comparison": "Baz ve senaryo sonuçlarının karşılaştırması",
  "Base and saved scenario results": "Baz hesap ve eklenen senaryoların sonuçları",
  "Small numbers show the change from the base case. Each result ends at its own final payment month. Margin changes are in percentage points. A dash means no borrowing was needed.": "Tutarların altındaki farklar baza göredir. Her hesap kendi son tahsilat ayına kadar sürer. Kâr marjı farkı yüzde puan olarak verilir. Borç oluşmayan hesapta en yüksek borç ayı “—” gösterilir.",
  "Project limits": "Kritik eşikler",
  "How far can one thing change before the base project misses a target? Each check changes only one input.": "Diğer koşullar sabitken baz proje ne kadar değişime dayanıyor? Her seferinde yalnızca bir değişken denenir.",
  "Minimum profit margin": "En düşük hedef kâr marjı",
  "Borrowing limit": "Kredi ihtiyacı sınırı",
  "Check limits": "Eşikleri hesapla",
  "Steel rise → loss": "Demir artışı → zarar",
  "Extra months → low margin": "Süre uzaması → hedef altı marj",
  "Payment delay → borrowing limit": "Tahsilat gecikmesi → kredi sınırı",
  "The selected cost item is checked from 0% to 1.000% in 0,01-point steps. Time and delay are checked in whole months. Matching a target is not a breach. These limits depend on your inputs.": "Seçilen kalem: %0–1.000 aralığında 0,01 yüzde puan adımla ilk zarar. Süre ve gecikme: tam ay adımla ilk aşım. Hedefe eşit değer aşım sayılmaz. Bunlar girilen plana bağlı hesap eşikleridir.",
  "Monthly cash balance": "Aylık nakit durumu",
  "Month-end cash balance for the base case and scenarios. Use the buttons above to show or hide lines. Exact values are in the monthly details below.": "Baz ve eklenen senaryolar için ay sonu nakit bakiyesi. Değerler aşağıdaki aylık dökümde hesap seçilerek görülebilir.",
  "Below zero means borrowing. Each line stops at its final payment month. Click a name above to show or hide its line. Hover over the chart for exact values.": "Eksi bakiye kredi borcudur. Her çizgi son tahsilat ayında biter. Yukarıdaki adlara basarak çizgileri açıp kapatabilir, grafiğin üzerine gelerek tutarları görebilirsiniz.",
  "Cost breakdown": "Hesabın dökümü",
  "Contract income": "Sözleşme geliri",
  "Work costs and overhead": "İş ve genel giderler",
  "Final cash / debt": "Son ay nakit / borç",
  "Includes starting cash.": "Başlangıç nakdi dahildir.",
  "Monthly details": "Aylık hesap dökümü",
  "Billing, payments, costs and interest": "Hakediş, tahsilat, gider ve faiz",
  "Choose which result to view using Summary and monthly details above.": "Gösterilen hesabı sonuçların üstündeki “Kartlar ve aylık döküm” alanından seçebilirsiniz.",
  "Monthly results": "Aylık hesap sonuçları",
  "Cash / debt": "Nakit / borç",
  "How does this calculation work?": "Bu hesap hangi varsayımlarla çalışıyor?",
  "Cash is checked at the end of each month. Short cash gaps within a month are not included.": "Hareketler ay sonunda netleştirilir; ay içindeki geçici nakit açıkları hesaplanmaz.",
  "Interest is charged on debt at the start of the month. Unpaid interest adds to the debt.": "Faiz, ay başındaki kredi borcuna uygulanır. Ödenemeyen faiz borca eklenir.",
  "Overhead stops when the work ends. The calculation runs until the last scheduled payment. Interest after that date is not included.": "İş bittiğinde genel gider durur. Hesap, son hakedişin tahsil edileceği aya kadar sürer; kalan borcun sonraki faizleri dahil değildir.",
  "Starting cash reduces borrowing but does not add to profit. The model assumes borrowing is available when needed.": "Başlangıç nakdi kârı artırmaz, kredi ihtiyacını azaltır. Kredi limiti sınırsız kabul edilir.",
  "Scenarios apply from the start of the project. Materials already bought are not tracked separately. Cost changes apply once, not every month.": "Senaryo tüm işin başlangıcından itibaren geçerlidir. Önceden satın alınmış malzeme ayrıca ayrılmaz. Maliyet yüzdeleri bir kez uygulanır; aylık bileşik artış değildir.",
  "Extra months mean slower progress. A 2-month plan stretched to 4 months spreads each old month over two new months. Work and contract value stay the same, but overhead continues. Change the labour percentage if needed.": "Uzama, çalışmanın daha yavaş ilerlemesi olarak modellenir. Örneğin 2 aylık plan 4 aya uzarsa her eski ay iki yeni aya yayılır. Sözleşme ve iş miktarı korunur; uzamanın ek doğrudan maliyeti genel giderdir. İşçilik için ayrıca yüzde değişimi girilebilir.",
  "Tax, deductions and price adjustment payments are not included. Results depend on the plan you enter.": "Vergi, kesinti ve fiyat farkı dahil değildir. Sonuçlar girilen plana bağlıdır.",
  "Enable JavaScript in your browser to use this calculator.": "Hesaplama aracını kullanmak için tarayıcınızda JavaScript'i etkinleştirin.",
  "Saved in this browser.": "Bu tarayıcıya kaydedildi.",
  "Could not save in this browser. You can save a file instead.": "Tarayıcı kaydı yapılamadı. Dosyaya kaydedebilirsiniz.",
  "Enter the contract value.": "Sözleşme bedelini girin.",
  "✓ Total billing matches the contract value.": "✓ Hakediş toplamı sözleşme bedeliyle eşleşiyor.",
  "Inputs changed. Calculate again to update the results.": "Girdiler değişti. Hesabı yeniden çalıştırın.",
  "Fields are ready. Add this scenario to compare it.": "Alanlar hazır. Hesaba katmak için karşılaştırmaya ekleyin.",
  "Same as the base case": "Baz koşullarla aynı",
  "Three scenarios added. Remove one to add another.": "Üç senaryo eklendi. Yeni bir tane eklemek için listeden birini silin.",
  "Only saved scenarios are compared. Editing these fields does not change the saved ones.": "Yalnızca listeye eklenen senaryolar karşılaştırılır. Alanları değiştirmek eklenenleri etkilemez.",
  "SCENARIO COMPARISON": "SENARYO KARŞILAŞTIRMASI",
  "No borrowing needed": "Kredi ihtiyacı oluşmuyor",
  "Enter your targets, then check the limits.": "Hedefleri tamamlayıp eşikleri hesaplayın.",
  "Base project already loses money": "Baz proje zaten zararda",
  "No loss up to +1.000%": "+%1.000’e kadar zarar yok",
  "No loss found in this range. Larger increases were not checked.": "Taranan aralıkta zarar eşiği bulunmadı. Daha yüksek artışlar için sonuç çıkarılamaz.",
  "Margin is not available": "Marj hesaplanamıyor",
  "Profit margin cannot be calculated with a zero contract value.": "Sözleşme bedeli sıfır olduğu için kâr marjı tanımsız.",
  "Base margin is below the target": "Baz marj hedefin altında",
  "No limit found in this range": "Aralıkta eşik bulunmadı",
  "No breach found in this range": "Aralıkta aşım bulunmadı",
  "Base borrowing is already over the limit": "Baz kredi ihtiyacı sınırı aşıyor",
  "Each check starts from the base project. Saved scenarios are not included in these checks.": "Her eşik baz projeden ayrı hesaplandı. Eklenen senaryolar bu eşiklere uygulanmaz.",
  "Targets changed. Check the limits again.": "Hedefler değişti. Eşikleri yeniden hesaplayın.",
  "Month of peak debt": "En yüksek borcun oluştuğu ay",
  "Final payment month": "Son tahsilat ayı",
  "Changes": "Değişen koşullar",
  "Original plan": "Başlangıç planı",
  "Enter a project name.": "Proje adını girin.",
  "Choose a name that differs from Base and the other scenarios.": "Baz ve diğer senaryolardan farklı bir ad seçin.",
  "You have reached the three-scenario limit.": "Üç senaryo sınırına ulaştınız.",
  "Change the fields to add another scenario.": "Alanları değiştirerek başka bir senaryo ekleyebilirsiniz.",
  "Draft changed. Add it to the comparison when ready. Saved scenarios stay the same.": "Taslak değişti. Hesaba katmak için karşılaştırmaya ekleyin; listedeki senaryolar aynı kalır.",
  "Base project changed. Calculate again to compare all scenarios with the updated base.": "Baz proje değişti. Eklenen senaryoları yeni bazla karşılaştırmak için yeniden hesaplayın.",
  "Stress example filled in. Give it a name and click Add to comparison.": "Örnek stres koşulları dolduruldu. İsim verip “Karşılaştırmaya ekle” düğmesine basın.",
  "Draft fields reset. Saved scenarios are unchanged.": "Taslak alanları sıfırlandı. Eklenen senaryolar korundu.",
  "Replace your current inputs with the example project?": "Mevcut girişler örnek projeyle değiştirilecek. Devam edilsin mi?",
  "Example loaded: a made-up six-month housing project.": "Örnek veriler yüklendi. Altı aylık kurgusal bir konut projesi gösteriliyor.",
  "Clear the form and replace the project saved in this browser?": "Form ve bu tarayıcıdaki proje kaydı boşaltılacak. Devam edilsin mi?",
  "Enter the details and monthly plan for a new project.": "Yeni bir proje için bilgileri ve aylık planı doldurun.",
  "File download started. Unfinished inputs are included too.": "Proje dosyasının indirilmesi başlatıldı. Yarım kalan girişler de dosyaya dahil edildi.",
  "Project file opened and calculated.": "Proje dosyası açıldı ve hesaplandı.",
  "Project file opened. Check the incomplete or inconsistent inputs, then calculate again.": "Proje dosyası açıldı. Eksik veya tutarsız girişleri tamamlayıp yeniden hesaplayın.",
  "Your last saved project is open.": "Bu tarayıcıdaki son projeniz açıldı.",
  "Saved draft opened. Complete or correct the inputs, then calculate again.": "Kaydedilmiş taslak açıldı. Eksik veya tutarsız girişleri tamamlayıp yeniden hesaplayın.",
  "Loaded from this browser.": "Bu tarayıcıdaki kayıt açıldı.",
  "Could not read the browser save. A blank form is open; you can open a backup file.": "Tarayıcı kaydı okunamadığı için boş form açıldı. Varsa yedek dosyanızı açabilirsiniz.",
  "Could not load the saved project. Your old save has not been replaced.": "Tarayıcı kaydı açılamadı; eski kaydınızın üzerine yazılmadı.",
  "The project file must be no larger than 1 MB.": "Proje dosyası en fazla 1 MB olabilir.",
  "Could not read this file. Choose a valid JSON project file.": "Dosya okunamadı. Geçerli bir JSON proje dosyası seçin.",
  "This is not a project from this calculator, or the file format is unsupported.": "Bu dosya İnşaat Hesap tarafından kaydedilmiş bir proje değil veya dosya biçimi desteklenmiyor.",
  "The project file has missing fields.": "Proje dosyasında eksik alanlar var.",
  "The project file has missing or invalid fields.": "Proje dosyasında eksik veya geçersiz alanlar var.",
  "The project file must contain a plan of 1–120 months.": "Proje dosyası 1–120 aylık bir plan içermeli.",
  "Work duration does not match the monthly plan in the file.": "Dosyadaki iş süresi aylık planla eşleşmiyor.",
  "Currency must be EUR, USD or TL.": "Para birimi EUR, USD veya TL olmalı.",
  "A project can have up to 3 scenarios.": "Projede en fazla 3 senaryo olabilir.",
  "Scenario names must be 1–60 characters long.": "Senaryo adı 1–60 karakter olmalı.",
  "Saved scenario changes are invalid.": "Kaydedilen senaryo koşulları geçersiz.",
  "Scenario names must differ from each other and from Base.": "Senaryo adları birbirinden ve Baz adından farklı olmalı.",
  "Scenario names must be no longer than 60 characters.": "Senaryo adı en fazla 60 karakter olabilir.",
  "A work plan with at least one month is required.": "En az bir aylık iş planı gerekli.",
  "Payment delay must be in whole months from 0 to 120.": "Tahsilat gecikmesi 0–120 arasında tam ay olmalı.",
  "Monthly interest rate must be between 0% and 100%.": "Aylık faiz oranı %0–100 arasında olmalı.",
  "Total monthly billing must equal the contract value.": "Aylık hakedişlerin toplamı sözleşme bedeline eşit olmalı.",
  "Extra time must be zero or positive whole months; total work duration cannot exceed 120 months.": "Ek süre sıfır veya pozitif tam ay olmalı; toplam iş süresi 120 ayı aşamaz.",
  "Extra delay must be zero or positive whole months; total payment delay cannot exceed 120 months.": "Ek gecikme sıfır veya pozitif tam ay olmalı; toplam tahsilat gecikmesi 120 ayı aşamaz.",
  "Target margin must be between 0% and 100%.": "Hedef marj %0–100 arasında olmalı.",
  "Enter a valid borrowing limit.": "Geçerli bir kredi sınırı girin.",
  "Enter an amount from 0 to 1.000.000.000.000. Use a comma and up to two digits for cents.": "0–1.000.000.000.000 arasında bir tutar girin. Kuruş için virgül ve en fazla iki basamak kullanın.",
  "Example housing project": "Örnek konut projesi",
  "Steel cost": "Demir maliyeti",
  "Concrete cost": "Beton maliyeti",
  "Labour cost": "İşçilik maliyeti",
  "Other costs": "Diğer maliyetler",
  "Language": "Dil",
  "Billed": "Hakediş",
  "Steel": "Demir",
  "Concrete": "Beton",
  "Labour": "İşçilik",
  "Other": "Diğer",
  "Total": "Toplam",
  "Month": "Ay",
  "month": "ay",
  "months": "ay",
  "mo": "ay",
  "Received": "Tahsilat",
  "Costs": "Gider",
  "Interest": "Faiz",
  "Loan interest": "Finansman",
  "Delay": "Gecikme",
  "Duration": "Süre",
  "Metric": "Gösterge",
  "Remove": "Sil",
  "Base": "Baz",
  "Start": "Başlangıç",
  "Compare the results": "Sonuçları karşılaştır",
  "Chart lines": "Grafik çizgileri",
  "All lines are hidden. Click a name above to show one.": "Tüm çizgiler kapalı. Göstermek için yukarıdan bir ad seçin.",
  "Language must be English or Turkish.": "Dil İngilizce veya Türkçe olmalı.",
  "Language changed. Your inputs are unchanged.": "Dil değişti. Girdiğiniz değerler aynı kaldı.",
  "Month {0}": "{0}. ay",
  "Month {0} {1} ({2})": "{0}. ay {1} ({2})",
  "Remove {0}": "{0} senaryosunu sil",
  "{0} / 3 scenarios": "{0} / 3 senaryo",
  "{0} · {1} · {2} months of work": "{0} · {1} · {2} aylık iş",
  "{0} · Cost breakdown": "{0} · Hesabın dökümü",
  "Monthly results for {0}, {1}": "{0} hesabının aylık sonuçları, {1}",
  "Base profit: {0}.": "Baz kâr: {0}.",
  "First loss: {0}. At +{1}%, profit was {2}.": "İlk zarar: {0}. Önceki +%{1} adımında kâr {2}.",
  "Base margin: {0}%. Target: {1}%.": "Baz marj %{0}. Hedef %{1}.",
  "Checked 0–{0} extra months. Total work duration is limited to 120 months.": "0–{0} ek ay tarandı. Toplam iş süresi en fazla 120 ay olabilir.",
  "At {0} months of work, the margin is {1}%. One month earlier: {2}%. Target: {3}%.": "Toplam {0} aylık işte marj %{1} olur. Önceki ay adımında %{2}. Hedef %{3}.",
  "Borrowing needed: {0}. Your limit: {1}.": "Gereken kredi {0}. Belirlediğiniz sınır {1}.",
  "Checked 0–{0} extra months of delay. Total delay is limited to 120 months.": "0–{0} ek gecikme ayı tarandı. Toplam gecikme en fazla 120 ay olabilir.",
  "With a total delay of {0} months, borrowing reaches {1}, which is {2} above the limit. One month earlier: {3}.": "Toplam {0} ay gecikmede kredi ihtiyacı {1} olur; sınır {2} aşılır. Önceki ay adımında {3}.",
  "Same base project · {0} scenarios": "Aynı baz proje · {0} farklı senaryo",
  "Show or hide {0}": "{0} çizgisini aç veya kapat",
  "Balance ({0})": "Bakiye ({0})",
  "Scenario {0}": "Senaryo {0}",
  "{0} percentage points": "{0} yüzde puan",
  "vs base {0}{1}": "Baza göre {0}{1}",
  "{0} added. {1}": "{0} eklendi. {1}",
  "{0} Your current inputs were kept.": "{0} Mevcut girişler korundu.",
  "Peak debt: month {0}": "En yüksek borç: {0}. ay",
  "Total billing is {0} short.": "Hakediş toplamı {0} eksik.",
  "Total billing is {0} too high.": "Hakediş toplamı {0} fazla.",
  "{0} removed from the comparison.": "{0} karşılaştırmadan çıkarıldı.",
  "Done. Calculated the base case and {0} scenarios.": "Hesap tamamlandı. Baz proje ve {0} senaryo hesaplandı.",
  "{0} must be zero or a positive number.": "{0} sıfır veya pozitif bir sayı olmalı.",
  "{0} change must be between -100% and 1000%.": "{0} değişimi %-100 ile %1000 arasında olmalı."
};

function setLanguage(value) {
  language = value === 'tr' ? 'tr' : 'en';
}

function t(text, ...values) {
  const translated = language === 'tr' ? turkish[text] ?? text : text;
  return translated.replace(/\{(\d+)\}/g, (_, index) => values[index] ?? '');
}

let pageText;
let attributes;
function translatePage() {
  pageText ??= [...document.querySelectorAll('[data-i18n]')].map((node) => [node, node.textContent]);
  if (!attributes) {
    attributes = [];
    const nodes = document.querySelectorAll('[placeholder], [aria-label], [title], meta[name="description"]');
    for (const node of nodes) {
      for (const name of ['placeholder', 'aria-label', 'title', 'content']) {
        if (node.hasAttribute(name)) attributes.push([node, name, node.getAttribute(name)]);
      }
    }
  }
  for (const [node, text] of pageText) if (node.isConnected) node.textContent = text.replace(text.trim(), t(text.trim()));
  for (const [node, name, text] of attributes) if (node.isConnected) node.setAttribute(name, t(text));
  document.documentElement.lang = language;
  document.title = t('Construction Calculator');
}
